version: "3"
services:

  ceph:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    environment:
      - CEPH_DEMO_UID=ceph-admin
      - CEPH_DEMO_ACCESS_KEY=accesskey
      - CEPH_DEMO_SECRET_KEY=secretkey
      - CEPH_DEMO_BUCKET=demobucket
      - RGW_NAME=ceph
      - RGW_CIVETWEB_PORT=8010
      - NETWORK_AUTO_DETECT=4
      - RESTAPI_LOG_LEVEL=debug
    ports:
      - 8010:8010
      - 5000:5000
    hostname: ceph
    command: demo

  postgres-server:
    image: wbaa/rokku-dev-apache-ranger-postgres:0.0.17

  ranger-admin:
    image: wbaa/rokku-dev-apache-ranger:0.0.19
    stdin_open: true
    tty: true
    depends_on:
      - "postgres-server"
      - "ceph"
    ports:
      - "6080:6080"

  rokku-sts:
    image: wbaa/rokku-sts:0.3.0
    environment:
      - STS_HOST=0.0.0.0
      - STS_PORT=12345
      - KEYCLOAK_PUBLIC_KEY_ID=FJ86GcF3jTbNLOco4NvZkUCIUmfYCqoqtOQeMfbhNlE
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_CHECK_REALM_URL=false
      - KEYCLOAK_CHECK_ISSUER_FOR_LIST=sts-rokku
      - MARIADB_URL=jdbc:mysql:loadbalance://mariadb:3306,mariadb:3306/rokku
    ports:
      - "12345:12345"
    depends_on:
      - "keycloak"
      - "mariadb"

  keycloak:
    image: wbaa/rokku-dev-keycloak:0.0.6
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"

  atlas:
    image: wbaa/rokku-dev-apache-atlas:0.0.8
    ports:
      - "21000:21000"
    depends_on:
      - "zookeeper"
      - "kafka"

  mariadb:
    image: wbaa/rokku-dev-mariadb:0.0.8
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3307:3306

  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "create_events:1:1,delete_events:1:1,ATLAS_HOOK:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  cassandra:
    image: cassandra:3
    container_name: cassandra
    ports:
      - "9042:9042"
      - "9160:9160"

  # command to mount bucket
  # alluxio fs mount --option aws.accessKeyId=accesskey --option aws.secretKey=secretkey --option alluxio.underfs.s3.endpoint=http://ceph:8010 --option alluxio.underfs.s3.inherit.acl=false --option alluxio.underfs.s3.disable.dns.buckets=true --option alluxio.underfs.s3.default.mode=0777 /alluxio s3://alluxio
  #
  alluxio-master:
    image: alluxio/alluxio
    ports:
      - "19999:19999"
      - "19998:19998"
    environment:
      ALLUXIO_JAVA_OPTS: "-Dalluxio.worker.memory.size=1G -Dalluxio.master.hostname=alluxio-master -Daws.accessKeyId=accesskey -Daws.secretKey=secretkey -Dalluxio.underfs.s3.endpoint=http://ceph:8010 -Dalluxio.master.mount.table.root.ufs=s3://demobucket -Dalluxio.underfs.s3.disable.dns.buckets=true"
    #volumes:
    #  - /opt/alluxio/underFSStorage:/opt/alluxio/underFSStorage
    command:
      master

  alluxio-worker:
    image: alluxio/alluxio
    ports:
      - "29999:29999"
      - "30000:30000"
    environment:
      ALLUXIO_JAVA_OPTS: "-Dalluxio.worker.memory.size=1G -Dalluxio.master.hostname=alluxio-master  -Dalluxio.worker.hostname=alluxio-worker -Daws.accessKeyId=accesskey -Daws.secretKey=secretkey -Dalluxio.underfs.s3.endpoint=http://ceph:8010 -Dalluxio.master.mount.table.root.ufs=s3://demobucket -Dalluxio.underfs.s3.disable.dns.buckets=true"
    volumes:
      - /opt/alluxio/ramdisk:/dev/shm
    #  - /opt/alluxio/underFSStorage:/opt/alluxio/underFSStorage
    command:
      worker

  alluxio-proxy:
    image: alluxio/alluxio
    ports:
      - "39999:39999"
    environment:
      ALLUXIO_JAVA_OPTS: "-Dlog4j.rootLogger=DEBUG -Dalluxio.worker.memory.size=1G -Dalluxio.master.hostname=alluxio-master  -Dalluxio.worker.hostname=alluxio-worker -Daws.accessKeyId=accesskey -Daws.secretKey=secretkey -Dalluxio.underfs.s3.endpoint=http://ceph:8010 -Dalluxio.master.mount.table.root.ufs=s3://demobucket -Dalluxio.underfs.s3.disable.dns.buckets=true"
    command:
      proxy
